version: 3

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - grafana-network
    volumes:
      - grafana:/var/lib/grafana
  influxdb:
    image: influxdb:1.0
    ports:
      - 8083:8083
      - 8086:8086
      - 25826:25826/udp
    networks:
      - grafana-network
    volumes:
      - influxdb:/var/lib/influxdb

networks:
  grafana-network:

volumes:
  grafana:
  influxdb:
